// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpMC3-vftDfEnslA9NJ0WYYvxSfhKdTU',
    appId: '1:582005089417:web:ef89c2424152652488d258',
    messagingSenderId: '582005089417',
    projectId: 'prjpab2-si6d-fe8fe',
    authDomain: 'prjpab2-si6d-fe8fe.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-fe8fe-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-fe8fe.firebasestorage.app',
    measurementId: 'G-VK2CG9SQ7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUTs4uLR4e6sV7ca_S_MZQ4EAePWsuaA',
    appId: '1:582005089417:android:761d12d836316f8988d258',
    messagingSenderId: '582005089417',
    projectId: 'prjpab2-si6d-fe8fe',
    databaseURL: 'https://prjpab2-si6d-fe8fe-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-fe8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWDu3wX44Ph6nHn0AK9tMqfhbMaw2p80',
    appId: '1:582005089417:ios:c6d5bee18b7a201688d258',
    messagingSenderId: '582005089417',
    projectId: 'prjpab2-si6d-fe8fe',
    databaseURL: 'https://prjpab2-si6d-fe8fe-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-fe8fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterDaftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWDu3wX44Ph6nHn0AK9tMqfhbMaw2p80',
    appId: '1:582005089417:ios:c6d5bee18b7a201688d258',
    messagingSenderId: '582005089417',
    projectId: 'prjpab2-si6d-fe8fe',
    databaseURL: 'https://prjpab2-si6d-fe8fe-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-fe8fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterDaftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpMC3-vftDfEnslA9NJ0WYYvxSfhKdTU',
    appId: '1:582005089417:web:e4570253ad0d2f1888d258',
    messagingSenderId: '582005089417',
    projectId: 'prjpab2-si6d-fe8fe',
    authDomain: 'prjpab2-si6d-fe8fe.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-fe8fe-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-fe8fe.firebasestorage.app',
    measurementId: 'G-DNQWW7NE02',
  );
}
