// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUmsA3VDiYnx-d91UCpM8uljKUF8nahw',
    appId: '1:10951648592:web:5fc771800918b7d43eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    authDomain: 'prjpab2-si6d-171129.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    measurementId: 'G-RG0CQMVC34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmIQC6poS-flazOY2tokDajSu69vnWdI',
    appId: '1:10951648592:android:053b42106f0848f33eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANa1YwhxOppXoSUF1u27HlwqTTqGySmMw',
    appId: '1:10951648592:ios:d97feaa145e83e913eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    iosBundleId: 'com.example.flutterDaftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANa1YwhxOppXoSUF1u27HlwqTTqGySmMw',
    appId: '1:10951648592:ios:d97feaa145e83e913eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    iosBundleId: 'com.example.flutterDaftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEUmsA3VDiYnx-d91UCpM8uljKUF8nahw',
    appId: '1:10951648592:web:c95d44ef2fec80ef3eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    authDomain: 'prjpab2-si6d-171129.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    measurementId: 'G-EPZWL7K66L',
  );
}
