// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUmsA3VDiYnx-d91UCpM8uljKUF8nahw',
    appId: '1:10951648592:web:3cb87ffa3529335b3eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    authDomain: 'prjpab2-si6d-171129.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    measurementId: 'G-53HHY5H8R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmIQC6poS-flazOY2tokDajSu69vnWdI',
    appId: '1:10951648592:android:2457c78175a6bc333eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANa1YwhxOppXoSUF1u27HlwqTTqGySmMw',
    appId: '1:10951648592:ios:7cc706c94dc78a693eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    iosClientId: '10951648592-sfmnqt69ng5t6lja128a072atsg2an2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumsi6d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANa1YwhxOppXoSUF1u27HlwqTTqGySmMw',
    appId: '1:10951648592:ios:7cc706c94dc78a693eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    iosClientId: '10951648592-sfmnqt69ng5t6lja128a072atsg2an2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumsi6d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEUmsA3VDiYnx-d91UCpM8uljKUF8nahw',
    appId: '1:10951648592:web:3cb87ffa3529335b3eb855',
    messagingSenderId: '10951648592',
    projectId: 'prjpab2-si6d-171129',
    authDomain: 'prjpab2-si6d-171129.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6d-171129-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6d-171129.firebasestorage.app',
    measurementId: 'G-53HHY5H8R3',
  );

}